version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: nuget sources add -Name dsharp-myget -Source https://www.myget.org/F/dsharpplus-nightly/api/v3/index.json
  - cmd: dotnet restore ./Yui/Yui.csproj --verbosity m
build_script:
  # output will be in ./Yui/bin/debug/netcoreapp2.1/publish
  - cmd: dotnet publish ./Yui/Yui.csproj
after_build:
  # For once the build has completed
artifacts:
  - path: Yui.zip
    name: Yui Release Build
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off
